title: L先生的博客
description: "L先生的博客,一个有趣而精彩的地方。"
url: "https://leliang-sjtu.github.io/" 
baseurl: "/jekyll-gitbook"  
theme: jekyll-theme-cayman  
exclude:  
  - "README.md"  
  - "LICENSE"  
plugins:  
  - jekyll-seo-tag  
  - jekyll-feed  
author: "John Doe"  
social_links:  
  github: "https://github.com//LeLiang-SJTU"  
google_analytics: UA-XXXXXXXX-X


# 构建设置
markdown: kramdown
permalink: /:year/:month/:day/:title/

# 导航设置
navigation:
  - title: 首页
    url: /
  - title: 关于
    url: /about
  - title: 归档
    url: /archive

# 分类设置
categories:
  - name: 技术博客
    items:
      - name: Web开发
        posts: []
      - name: 人工智能
        posts: []
  - name: 生活随笔
    items:
      - name: 旅行日记
        posts: []
      - name: 读书笔记
        posts: []